### ISSUE TITLE
How to Update a Candidate Status from Form Script

### ISSUE THREAD

**Issue by ss513546039** [bullhorn/bullhornjs#5]
After a certain validation, we need to update the candidate status to Screened etc., so please provide any suggestion or sample code to refer. 

we tried using ajax, but call is not going through successfully. Bullhorn passing different candidate id than what we are seeing in the UI, please find the details below

From  bullhorn side:
https://bhnext.bullhornstaffing.com/BullhornStaffing/Update/UpdEntities.cfm?updKey=7%3BG%5E7%40U%5E%5FCH%2A%3EMN%5C%20U%3CO%23R%3B%27%25F1ZJD80%20%0A&keyColumn=candidateID&candidateID=823550&ID=823550&status=Active&entity=Candidate&saratogaEntityName=Candidate&updColumns=status&updTypes=String&&doNotAlert=TRUE&reloadOpener=FALSE&closeOnFinish=TRUE&nocache=1491656662331

From ACS side:

https://bhnext.bullhornstaffing.com/BullhornStaffing/Update/UpdEntities.cfm?updKey=7%3BG%5E7%40U%5E%5FCH%2A%3EMN%5C%20U%3CO%23R%3B%27%25F1ZJD80%20%0A&keyColumn=candidateID&candidateID=920373&ID=920373&status=New%20Lead&entity=Candidate&saratogaEntityName=Candidate&updColumns=status&updTypes=String&&doNotAlert=TRUE&reloadOpener=FALSE&closeOnFinish=TRUE&nocache=1491647394386

Thanks,
Suresh

**Comment by bvkimball** [comment]
Hi Suresh,

So I think what you are describing would be better suited as a Form Trigger which is a ServerSide hook that will pre-validate before saving the record, you can manipulate the packet prior to save or return a validation error.

FormScripts are for real-time validations or manipulation of the form at runtime.  You would need to use JS to get the FORM on the page and override the Submit action or listen to 'change' events on the inputs that are related to the Validation.  onChange you could use JS to populate the Form Input for status to equal *Screened*

From your initial description a FormTrigger would be a better fit.

Brian

**Comment by harigkp** [comment]
Hey bvkimball,
Here we are working on form script, why go to form trigger for small thing. If more than one data update and java scripts not validating properly then makes sense to go form trigger.
This is just ajax fire for updating status only based on candidate id.
If Bullhorn ajax is doing successful then why not our code working correctly, every time showing illegal operation.

Please see Ajax URL carefully here candidate id different in your ajax and accurate candidate id in our ajax URL. 
Can you tell me why different candidate id in your AJAX URL and what is the concept behind this. Or are you passing something else.

**Comment by ss513546039** [comment]
understand but is any way we can achieve through form script, its good if we can achieve it by form script, otherwise we need to go back to form trigger for this one process alone and again time consuming process.

Thanks,
Suresh Somasundaram

**Comment by ss513546039** [comment]
or could you please provide the service details, so will call the service and update the status accordingly.
Thanks,
Suresh Somasundaram

**Comment by ss513546039** [comment]
We are able to figure out how to update the status from form script. 

Thanks,
Suresh Somasundaram
